name: Node.js CI
on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: curl -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
    - run: sudo apt-get install unzip
    - run: unzip sonar-scanner-cli-4.4.0.2170-linux.zip
    - run: /home/runner/work/React-Switch-Card-Color/React-Switch-Card-Color/sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner -D"sonar.projectKey=Switch" -D"sonar.sources=." -D"sonar.host.url=http://13.235.49.156/" -D"sonar.login=b08141a54701218e14d013b4820f282a266e6c46"
